<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '彩妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '彩妆',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '眼部彩妆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '眼部彩妆',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '眉粉眉笔',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '50',
    'name' => '眉粉眉笔',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '眼线',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '47',
    'name' => '眼线',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '48',
    'name' => '眼影',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '睫毛',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '49',
    'name' => '睫毛',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '面部彩妆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 3,
    'level' => 1,
    'id' => '5',
    'name' => '面部彩妆',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '散粉',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '54',
    'name' => '散粉',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'BB霜',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '51',
    'name' => 'BB霜',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '隔离霜',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '55',
    'name' => '隔离霜',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '粉底',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '52',
    'name' => '粉底',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '粉饼',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '53',
    'name' => '粉饼',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '彩妆套装',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '4',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 4,
    'level' => 1,
    'id' => '3',
    'name' => '彩妆套装',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '浓密卷翘',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '60',
    'name' => '浓密卷翘',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '修容',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '57',
    'name' => '修容',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '润唇',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '58',
    'name' => '润唇',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '59',
    'name' => '卸妆',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '56',
    'name' => '眼影',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '其他彩妆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 2,
    'level' => 1,
    'id' => '2',
    'name' => '其他彩妆',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '底妆定妆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '底妆定妆',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '美甲',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '美甲',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '修容',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '修容',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '腮红',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '腮红',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '遮瑕',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '遮瑕',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '唇妆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '62',
    'name' => '唇妆',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '美容工具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '美容工具',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '美体工具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '130',
    'name' => '美体工具',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '美甲工具',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '美甲工具',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '瘦身纤体',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '瘦身纤体',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '化妆工具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '71',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '131',
    'name' => '化妆工具',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '辅助化妆',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '辅助化妆',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '定妆',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => '定妆',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '艾黛儿',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '艾黛儿',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '化妆镜',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '化妆镜',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '美发工具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '72',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '132',
    'name' => '美发工具',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '护发养发',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '护发养发',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '发型定型',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '发型定型',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '日用收纳',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '73',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '133',
    'name' => '日用收纳',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '化妆包',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '化妆包',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '雅诗兰黛',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '144',
    'name' => '雅诗兰黛',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '收纳',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '142',
    'name' => '收纳',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '男士',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '男士',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '面部护理',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '面膜',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '眼霜',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '眼霜',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '67',
    'name' => '洁面',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '71',
    'name' => '精华',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '爽肤',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '爽肤',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '72',
    'name' => '面霜',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '乳液',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '身体护理',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '香体喷雾',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '香体喷雾',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '阿迪达斯',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '77',
    'name' => '阿迪达斯',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '沐浴',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '清洁',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '清洁',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '其他护理',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '其他护理',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '剃须',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '剃须',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => 'BB霜',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => 'BB霜',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '防晒',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '男士套装',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '男士套装',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '活肤',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => '活肤',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '兰芝',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '83',
    'name' => '兰芝',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '欧莱雅',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '84',
    'name' => '欧莱雅',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '保湿',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '碧欧泉',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '85',
    'name' => '碧欧泉',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '香氛',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '香氛',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '女士香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '3',
    'level' => 1,
    'id' => '86',
    'name' => '女士香水',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '迪奥',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '92',
    'name' => '迪奥',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '安娜苏',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '93',
    'name' => '安娜苏',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '淡香',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '菲拉格慕',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '94',
    'name' => '菲拉格慕',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '花香调',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '花香调',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '男士香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '5',
    'goods_num' => '2',
    'level' => 1,
    'id' => '87',
    'name' => '男士香水',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '宝格丽',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '宝格丽',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '淡香',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '阿迪达斯',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '阿迪达斯',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '海洋香调',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '海洋香调',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '博柏利',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '博柏利',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '中性香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '4',
    'goods_num' => '1',
    'level' => 1,
    'id' => '88',
    'name' => '中性香水',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '爱马仕',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '爱马仕',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '凯文克莱',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '凯文克莱',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '淡香',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '花果香调',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '花果香调',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '香水套装',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '香水套装',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '草木香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '草木香调',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '香体',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '香体',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '花香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '花香调',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '花果香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '花果香调',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '104',
    'name' => '淡香',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '护肤',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '眼部护理',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '12',
    'level' => 1,
    'id' => '8',
    'name' => '眼部护理',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '去眼袋',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '31',
    'name' => '去眼袋',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '保湿',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '去黑眼圈',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '去黑眼圈',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '去浮肿',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '去浮肿',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '去眼纹',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '30',
    'name' => '去眼纹',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '其他护理',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '其他护理',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '喷雾',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '喷雾',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'T区护理',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '38',
    'name' => 'T区护理',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '啫喱',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '啫喱',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '颈霜',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '39',
    'name' => '颈霜',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '角质按摩',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '36',
    'name' => '角质按摩',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '护唇',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '33',
    'name' => '护唇',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '保健食品',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '保健食品',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '祛痘祛斑',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '37',
    'name' => '祛痘祛斑',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '护肤套装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '6',
    'level' => 1,
    'id' => '11',
    'name' => '护肤套装',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '补水',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '44',
    'name' => '补水',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '美白',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '美白',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '紧致去皱',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '45',
    'name' => '紧致去皱',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '42',
    'name' => '保湿',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '嫩肤',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '43',
    'name' => '嫩肤',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '面部护理',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '25',
    'name' => '乳液',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '22',
    'name' => '防晒',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '31',
    'level' => 2,
    'id' => '19',
    'name' => '洁面',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '26',
    'name' => '面霜',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '23',
    'name' => '精华',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '20',
    'name' => '面膜',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '面油',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '面油',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '化妆水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '24',
    'name' => '化妆水',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '21',
    'name' => '卸妆',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '身体护理',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '5',
    'goods_num' => '1',
    'level' => 1,
    'id' => '109',
    'name' => '身体护理',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '脱毛',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '脱毛',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '手足护理',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '115',
    'name' => '手足护理',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '香体止汗',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '香体止汗',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '113',
    'name' => '沐浴',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '其他护理',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '117',
    'name' => '其他护理',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '丰胸瘦身',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '丰胸瘦身',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '丰胸塑臀',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '118',
    'name' => '丰胸塑臀',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '纤体瘦身',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '119',
    'name' => '纤体瘦身',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '精油护理',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '120',
    'name' => '精油护理',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '美发护发',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '62',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '美发护发',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '焗油',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '焗油',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '洗发',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '美发造型',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '美发造型',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '护发',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '染发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '染发',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '洗护套装',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '63',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '洗护套装',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '沐浴',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '护发养发',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '护发养发',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '美体套装',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '129',
    'name' => '美体套装',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '126',
    'name' => '保湿',
  ),
);
?>